version: '3.7'

volumes:
  volume-test:

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbit1"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - my-network
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_DATABASE: evaluation
  mysql:
    image: mysql:latest
    container_name: "mysql"
    networks:
      - my-network
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: "always"
    ports:
      - "3306:3306"
    volumes:
      - volume-test:/var/lib/mysql
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    networks:
      - my-network
    ports:
      - "9411:9411"
    environment:
      - JAVA_OPTS=-Dspring.zipkin.base-url=http://zipkin:9411

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: "keycloak-ms"
    ports:
      - "8180:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=H2
      - KEYCLOAK_BIND=0.0.0.0
    command:
      - "start-dev"
      - "--import-realm"
    volumes:
      - ./export.json:/opt/keycloak/data/import/realm.json
    networks:
      - my-network

  discovery-server:
    container_name: discovery-service
    ports:
      - '8761:8761'
    image: medaminer/discovery-server:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - my-network

  api-gateway:
    container_name: api-gateway
    ports:
      - '9092:9092'
    image: medaminer/api-gateway:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - user-management
      - discovery-server
      - zipkin
    networks:
      - my-network
  user-management:
    container_name: user-management
    ports:
      - '9095:9095'
    image: medaminer/user-management:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - my-network
    depends_on:
      - keycloak
      - discovery-server
      - zipkin
  self-service-portal:
    container_name: self-service-portal
    ports:
      - '9090:9090'
    image: medaminer/self-service-portal:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - my-network
    depends_on:
      - user-management
      - mysql
      - discovery-server
      - zipkin
      - rabbitmq
  project-manager-portal:
    container_name: project-manager-portal
    ports:
      - '9091:9091'
    image: medaminer/project-manager-portal:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - my-network
    depends_on:
      - user-management
      - self-service-portal
      - mysql
      - discovery-server
      - zipkin
      - rabbitmq
  evaluation-portal:
    container_name: evaluation-portal
    ports:
      - '9096:9096'
    image: medaminer/evaluation-portal:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - my-network
    depends_on:
      - user-management
      - discovery-server
      - zipkin
      - mongo


networks:
  my-network:
    driver: bridge
